final List<String> arabicDessertNames = [
  'Basbousa',
  'Baklava',
  'Maamoul',
  'Knafeh Nabulsieh',
  'Halawet el Jibn',
  'Qatayef',
  'Awamat (Luqaimat)',
  'Zalabia',
  'Mhallabiyeh',
  'Umm Ali',
  'Eish el Saraya',
  'Asabe Zainab (Zainab’s Fingers)',
  'Atayef Asafiri',
  'Rice Pudding (Roz Bel Laban)',
  'Semolina Cake (Harissa)',
  'Tahini Halva',
  'Date Rolls',
  'Date Maamoul',
  'Fig Maamoul',
  'Pistachio Maamoul',
  'Stuffed Dates',
  'Almond-Stuffed Figs',
  'Halva with Nuts',
  'Sweet Couscous with Dates',
  'Sahlab (Hot Milk Drink)',
  'Carob Molasses Sweets',
  'Turmeric Cake (Sfouf)',
  'Makroud (Date Semolina Bar)',
  'Magrood (Libyan Date Bars)',
  'Fakhfakhina (Fruit Dessert)',
  'Sweet Vermicelli (She’reya)',
  'Honey Almond Fingers',
  'Jazarieh (Candied Carrots)',
  'Mabroom Dates with Nuts',
  'Qamar al-Din Pudding (Apricot)',
  'Sweet Cheese Rolls',
  'Kishk Halabi (Sweetened)',
  'Sweet Ghraybeh (Shortbread)',
  'Dibs bi Tahini (Molasses with Tahini)',
  'Khabeesa (Gulf-style sweet)',
  'Kunafa with Cream',
  'Kunafa with Mango',
  'Kunafa with Nutella',
  'Semsmiyah (Sesame Bars)',
  'Jawziyeh (Walnut Candy)',
  'Hab Al Hal (Cardamom Cookies)',
  'Date Fudge',
  'Sweet Tahini Rolls',
  'Orange Blossom Pistachio Cake',
  'Milk & Honey Semolina Pudding',
];
