const List<String> arabicRecipes = [
  "Arabic Rice",
  "Arabic Salad",
  "Arayes (Stuffed Pita)",
  "Baba Ganoush",
  "Bamya (Okra Stew)",
  "Batata Harra (Spicy Potatoes)",
  "Fatteh",
  "Fatayer (Stuffed Pastry)",
  "Fattah",
  "Fattoush",
  "Falafel",
  "Foul Medames (Fava Beans)",
  "Grilled Halloumi",
  "Harees (Wheat & Meat Porridge)",
  "Harira Soup",
  "Hummus",
  "Kabsa (Spiced Rice & Meat)",
  "Kafta Bil Sanieh (Baked Meatballs)",
  "Kebbeh (Meat & Bulgur Croquettes)",
  "Kibbeh Nayeh (Raw Kibbeh)",
  "Khubz (Arabic Bread)",
  "Labneh (Strained Yogurt)",
  "Lamb Mandi",
  "Lamb Shawarma",
  "Lamb Tagine",
  "Lentil Soup",
  "Magloubeh (Upside-down Rice)",
  "Makloubeh",
  "Manakish (Flatbread with Toppings)",
  "Mansaf (Lamb with Yogurt Sauce)",
  "Maraq (Meat Stew)",
  "Masakhan (Sumac Chicken with Onions)",
  "Mejadra (Lentils & Rice)",
  "Mloukhieh (Jute Leaves Stew)",
  "Moussaka (Eggplant Casserole)",
  "Muhammara (Red Pepper Dip)",
  "Mutabbaq (Stuffed Pancake)",
  "Mutton Kebab",
  "Mushabbak (Layered Pastry)",
  "Okra Stew",
  "Omani Shuwa (Slow Cooked Lamb)",
  "Ouzi (Rice and Meat Stuffed Pastry)",
  "Pita Bread",
  "Qidra (Rice and Meat Dish)",
  "Ruz Bukhari (Saudi Rice)",
  "Ruz Ma’ Laban (Rice with Yogurt)",
  "Samak Harra (Spicy Fish)",
  "Samak Mashwi (Grilled Fish)",
  "Sfiha (Meat Pies)",
  "Shakshuka",
  "Shish Tawook (Grilled Chicken Skewers)",
  "Soujouk (Spicy Sausage)",
  "Spinach Fatayer",
  "Stuffed Grape Leaves (Warak Enab)",
  "Stuffed Zucchini",
  "Tabbouleh",
  "Tahini",
  "Tahini Sauce",
  "Tajin (Moroccan Stew)",
  "Tameya (Egyptian Falafel)",
  "Warak Enab (Stuffed Grape Leaves)",
  "Za’atar Bread",
  "Zaatar Manakish (Flatbread with Za’atar)",
  "Zereshk Polo (Barberry Rice)",
  "Zucchini Fritters",
  "Zucchini Stew",
  "Balila (Chickpea Salad)",
  "Bamieh bil Zeit (Okra in Olive Oil)",
  "Bayd Bi Tom (Egg with Garlic Sauce)",
  "Dajaj Mashwi (Grilled Chicken)",
  "Dajaj Mahshi (Stuffed Chicken)",
  "Dibs (Date Syrup used in cooking)",
  "Fasoulia (Green Beans Stew)",
  "Fattoush Salad",
  "Freekeh (Roasted Green Wheat Dish)",
  "Gheymeh (Yellow Split Pea Stew)",
  "Hmiss (Spicy Pepper Salad)",
  "Imam Bayildi (Stuffed Eggplant)",
  "Jareesh (Cracked Wheat with Meat)",
  "Jibneh Arabieh (Arabic Cheese)",
  "Kabsa with Chicken",
  "Kofta (Meatballs)",
  "Kofta bil Laban (Meatballs in Yogurt Sauce)",
  "Kousa Mahshi (Stuffed Zucchini)",
  "Loubieh Bi Zeit (Green Beans in Olive Oil)",
  "Mahshi (Stuffed Vegetables)",
  "Malfouf (Stuffed Cabbage)",
  "Mansaf bil Dajaj (Chicken Mansaf)",
  "Marag (Meat Soup)",
  "Mtabbal (Eggplant Dip)",
  "Musakhan Bil Dajaj (Sumac Chicken)",
  "Mujaddara with Yogurt",
  "Murtabak (Stuffed Flatbread)",
  "Nakhleih (Palm Seed Dish)",
  "Qara' bil Laban (Pumpkin in Yogurt)",
  "Qidra with Chicken",
  "Ruz bil Dajaj (Chicken Rice)",
  "Samak Sayyadiyah (Fish with Rice)",
  "Sayadiyah (Fish and Rice)",
  "Shorbat Adas (Lentil Soup)",
  "Siniyah (Baked Meat and Rice)",
  "Spinach with Lamb",
  "Stuffed Peppers",
  "Tahini with Lemon",
  "Tameya (Egyptian Falafel)",
  "Yalanji (Stuffed Grape Leaves Vegetarian)",
  "Za’atar with Olive Oil",
  "Zigni (Spicy Stew)",
];
