const List<String> chineseRecipes = [
  "Beef and Broccoli",
  "Beef Chow Fun",
  "Chicken and Cashew Nuts",
  "Chicken Chow Mein",
  "Chicken Fried Rice",
  "Chicken Stir Fry",
  "Chinese Broccoli with Oyster Sauce (use halal oyster sauce)",
  "Chinese Cabbage Stir Fry",
  "Chinese Eggplant with Garlic Sauce",
  "Chinese Hot Pot (halal meat only)",
  "Chinese Noodles",
  "Chinese Scallion Pancakes",
  "Chinese Steamed Fish",
  "Congee (without pork)",
  "Crispy Duck (halal duck)",
  "Dan Dan Noodles (halal version)",
  "Dim Sum (Halal versions)",
  "Dim Sum Dumplings (Halal Filling)",
  "Duck Soup (halal duck)",
  "Egg Drop Soup",
  "Egg Foo Young",
  "Egg Fried Rice",
  "Eggplant with Garlic Sauce",
  "Fried Rice (without pork)",
  "Fried Wontons (Halal Filling)",
  "Garlic Bok Choy",
  "Garlic Shrimp",
  "General Tso's Chicken",
  "General Tso's Tofu",
  "Ginger Chicken",
  "Gong Bao Chicken",
  "Green Beans with Garlic Sauce",
  "Hainanese Chicken Rice",
  "Honey Chicken",
  "Honey Walnut Shrimp",
  "Hot and Sour Noodles",
  "Hot and Sour Soup",
  "Hot Pot (halal meats only)",
  "Kung Pao Chicken",
  "Kung Pao Shrimp",
  "Kung Pao Tofu",
  "Lemon Chicken",
  "Lo Mein",
  "Lo Mein Noodles",
  "Lo Mein with Vegetables",
  "Ma Po Tofu",
  "Mala Hot Pot (halal meats)",
  "Mapo Doufu",
  "Mongolian Beef",
  "Mu Shu Chicken (no pork, halal version)",
  "Orange Chicken",
  "Peking Duck (ensure halal duck)",
  "Pineapple Fried Rice",
  "Potstickers (Halal Fillings)",
  "Salt and Pepper Chicken",
  "Salt and Pepper Shrimp",
  "Shanghai Noodles",
  "Shrimp Fried Rice",
  "Sichuan Beef",
  "Sichuan Beef Stir Fry",
  "Sichuan Chicken",
  "Sichuan Hot Pot (halal meats only)",
  "Sichuan Tofu",
  "Spring Rolls (Vegetable or Halal Meat)",
  "Steamed Buns (Halal Filling)",
  "Sweet and Sour Chicken",
  "Szechuan Chicken",
  "Tea Eggs",
  "Tea Smoked Duck (Halal Duck)",
  "Three Cup Chicken",
  "Tofu Stir Fry",
  "Vegetable Chow Mein",
  "Vegetable Fried Rice",
  "Vegetable Spring Rolls",
  "Wonton (Halal Filling)",
  "Wonton Noodle Soup (Halal Filling)",
  "Wonton Soup (Halal Filling)",
  "Xiao Long Bao (Halal Filling)",
  "Yangzhou Fried Rice",
  "Yuxiang Eggplant",
  "Zha Jiang Mian",
  "Zhejiang Fried Noodles",
];