const List<String> pakistaniRecipes = [
  "Aloo Keema",
  "Aloo Palak",
  "Beef Biryani",
  "Bhindi Masala",
  "Chapli Kebab",
  "Chicken Biryani",
  "Chicken Karahi",
  "Chicken Korma",
  "Chicken Pulao",
  "Chicken Tikka",
  "Dal Chawal",
  "Dal Makhani",
  "Fish Curry",
  "Gosht Aloo",
  "Haleem",
  "Kadhi Pakora",
  "Kofta Curry",
  "Lahori Chargha",
  "Mutton Biryani",
  "Mutton Korma",
  "Mutton Pulao",
  "Nihari",
  "Palak Gosht",
  "Paya",
  "Pulao",
  "Qeema",
  "Seekh Kebab",
  "Siri Paye",
  "Tandoori Chicken",
  "Tandoori Roti",
  "Chapli Kabab",
  "Aloo Keema Curry",
  "Bheja Fry",
  "Chicken Handi",
  "Chicken Rezala",
  "Chicken Saagwala",
  "Chana Masala",
  "Dahi Bhalla",
  "Gajar Halwa (exclude if dessert)",
  "Gosht Nihari",
  "Kaleji Masala",
  "Karahi Gosht",
  "Kofta Nargisi",
  "Lassi",
  "Mughlai Chicken",
  "Murgh Cholay",
  "Palak Paneer (Pakistani Style)",
  "Paya",
  "Roghani Naan",
  "Saag",
  "Seekh Kabab",
  "Shami Kabab",
  "Tikka Masala",
  "Yakhni Pulao",
  "Mint Raita",
  "Onion Salad",
  "Cucumber Raita",
  "Green Chutney",
  "Tamarind Chutney",
  "Masala Chai",
  "Kashmiri Chai",
  "Chana Dal",
  "Masoor Dal",
  "Khichdi",
  "Boti Kebab",
  "Chicken Malai Boti",
  "Beef Kebab",
  "Keema Matar",
  "Aloo Tikki",
  "Pani Puri",
  "Gol Gappay",
  "Pakora",
  "Samosa",
  "Naan",
  "Paratha",
  "Rumali Roti",
  "Chicken Rezala",
  "Fish Fry",
  "Chicken Soup",
  "Beef Curry",
  "Mutton Curry",
  "Chapli Kabab with Yogurt Dip",
  "Aloo Chaat",
  "Dahi Puri",
  "Chicken Sheekh",
  "Vegetable Pulao",
  "Mixed Vegetable Curry",
  "Tarka Dal",
  "Kofta Curry with Gravy",
  "Beef Korma",
  "Chicken Jalfrezi",
  "Mutton Keema",
  "Chicken Haleem",
  "Peshawari Naan",
  "Butter Chicken (Pakistani Style)",
  "Chicken Samosa",
];
