const List<String> south_asianRecipes = [
  "Aloo Baingan",
  "Aloo Gobi",
  "Aloo Matar",
  "Aloo Paratha",
  "Baingan Bharta",
  "Bhindi Masala",
  "Bhuna Gosht",
  "Chicken 65",
  "Chicken Biryani",
  "Chicken Chettinad",
  "Chicken Curry",
  "Chicken Handi",
  "Chicken Hyderabadi",
  "Chicken Jalfrezi",
  "Chicken Kadai",
  "Chicken Korma",
  "Chicken Malai Tikka",
  "Chicken Saagwala",
  "Chicken Seekh Kebab",
  "Chicken Tikka Masala",
  "Chole Bhature",
  "Dal Fry",
  "Dal Makhani",
  "Dum Aloo",
  "Gobi Manchurian",
  "Goan Fish Curry",
  "Gosht Aloo",
  "Hara Bhara Kabab",
  "Hyderabadi Biryani",
  "Idli Sambar (with lentils)",
  "Kadai Paneer",
  "Kadhi Pakora",
  "Keema Matar",
  "Kofta Curry",
  "Kofta Nargisi",
  "Lamb Vindaloo",
  "Lamb Rogan Josh",
  "Lamb Shikampuri Kebab",
  "Malai Kofta",
  "Matar Paneer",
  "Methi Aloo",
  "Methi Murg",
  "Methi Paneer",
  "Misal Pav (South Asian curry)",
  "Mughali Chicken",
  "Mutton Biryani",
  "Mutton Curry",
  "Mutton Keema",
  "Navratan Korma",
  "Paneer Bhurji",
  "Paneer Butter Masala",
  "Paneer Korma",
  "Paneer Tikka",
  "Pav Bhaji",
  "Pesarattu",
  "Poha (savory rice dish)",
  "Punjabi Kadhi",
  "Punjabi Lamb Curry",
  "Pulao",
  "Rajma Masala",
  "Rasam (savory soup)",
  "Saag Paneer",
  "Sambar Rice (savory stew)",
  "Simple Chicken Curry",
  "Soya Keema Curry",
  "Soya Chaap Masala",
  "Tandoori Chicken",
  "Tawa Paneer",
  "Tava Masala Chicken",
  "Tomato Butter Curry",
  "Vegetable Biryani",
  "Vegetable Jalfrezi",
  "Vegetable Korma",
  "Vegetable Pulao",
  "Vegetable Tikka Masala",
  "Veg Cutlet (savory patty)",
  "Veg Manchurian (gravy version)",
  "Vindaloo (Chicken or Lamb)",
  "Zunka Bhakri (savory dhal)",
  "Rogan Josh (mutton curry)",
  "Murgh Cholay",
  "Dal Tadka",
  "Fish Moilee (Kerala)",
  "Prawn Curry",
  "Egg Curry",
  "Beetroot Curry",
  "Kashmiri Dum Aloo",
  "Paneer Do Pyaza",
  "Chicken Rezala",
  "Keema Paratha (savory stuffed bread)",
  "Paneer Pasanda",
  "Bhuri Roti (stuffed bread)",
  "Khichdi (savory lentil rice)",
  "Gujarati Dal Dhokli",
  "Prawn Malai Curry",
  "Egg Biryani",
];
